# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 18:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Add updates here')),
                ('author', models.CharField(default='Add Author', max_length=40)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('red_flag', models.BooleanField(default=None)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Id', models.CharField(choices=[('wcc-sw-nfa', 'wcc-sw-nfa'), ('wcc-sw-wiced-stack', 'wcc-sw-wiced-stack')], default='Add Project ID here', max_length=140)),
                ('subcategory_Id', models.CharField(choices=[('NFA11', 'NFA11'), ('NFA20', 'NFA20'), ('NFCA 3.0', 'NFCA 3.0'), ('BTEWICED 2.0', 'BTEWICED 2.0')], default='Add Sub Project ID here', max_length=140)),
                ('title', models.CharField(blank=True, default='', max_length=140)),
                ('created_date', models.DateField(auto_now=True)),
                ('State', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='New', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(max_length=400, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=6)),
                ('hasparent', models.NullBooleanField()),
                ('haschildren', models.NullBooleanField()),
                ('parentId', models.IntegerField(default=0)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(default='99', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.Item'),
        ),
    ]
