# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='State',
            field=models.CharField(choices=[('New Item', 'New'), ('Task In Progress', 'In Progress'), ('Task Completed', 'Complete')], default='New', max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(default='99', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=6),
        ),
    ]
