# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160210_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='time_allocated',
        ),
        migrations.AddField(
            model_name='comment',
            name='red_flag',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='todo.Comment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(default='99', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
