# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_disqus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disqus',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='99', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.Item'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Disqus',
        ),
    ]
