# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20160210_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='project_Id',
        ),
        migrations.AddField(
            model_name='item',
            name='Project_Id',
            field=models.CharField(default='wcc', max_length=150),
        ),
    ]
