# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20160215_1610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='list',
            name='group',
        ),
        migrations.RemoveField(
            model_name='item',
            name='list',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
