# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20160215_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Add Author', max_length=40),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='No updates'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
