# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20160219_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Project_Id',
            field=models.CharField(choices=[('wcc-sw-nfa', 'wcc-sw-nfa'), ('wcc-sw-wiced-stack', 'wcc-sw-wiced-stack')], default='Add Project ID here', max_length=140),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory_Id',
            field=models.CharField(choices=[('NFA11', 'NFA11'), ('NFA20', 'NFA20'), ('NFCA 3.0', 'NFCA 3.0'), ('BTEWICED 2.0', 'BTEWICED 2.0')], default='Add Sub Project ID here', max_length=140),
        ),
    ]
