# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20160219_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isparent',
            field=models.BooleanField(default=False),
        ),
    ]
