# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0014_item_isparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_created_date', models.DateField(auto_now=True)),
                ('ct_State', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='New', max_length=16)),
                ('ct_due_date', models.DateField(blank=True, null=True)),
                ('ct_completed_date', models.DateField(blank=True, null=True)),
                ('ct_note', models.TextField(max_length=400, null=True)),
                ('ct_priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=6)),
                ('childtask', models.ForeignKey(default='99', on_delete=django.db.models.deletion.CASCADE, related_name='childtasks', to='todo.Item')),
                ('ct_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_todo_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('ct_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_todo_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('ct_priority',),
            },
        ),
    ]
