# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_childtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='childtask',
            name='title',
            field=models.CharField(default='Add Title here', max_length=140),
        ),
    ]
