# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_childtask_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childtask',
            options={'ordering': ('priority',)},
        ),
        migrations.RenameField(
            model_name='childtask',
            old_name='ct_State',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='childtask',
            old_name='ct_assigned_to',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='childtask',
            old_name='ct_completed_date',
            new_name='completed_date',
        ),
        migrations.RenameField(
            model_name='childtask',
            old_name='ct_created_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='childtask',
            old_name='ct_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='childtask',
            old_name='ct_due_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='childtask',
            old_name='ct_note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='childtask',
            old_name='ct_priority',
            new_name='priority',
        ),
        migrations.AddField(
            model_name='childtask',
            name='isparent',
            field=models.BooleanField(default=False),
        ),
    ]
