# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20160229_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childtask',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=140),
        ),
    ]
