# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_auto_20160229_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isparent',
        ),
        migrations.AddField(
            model_name='item',
            name='hasparent',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='item',
            name='parentId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
