# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_item_haschildren'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='aux_show',
            field=models.NullBooleanField(),
        ),
    ]
