# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_item_aux_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='aux_show',
        ),
    ]
