# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_remove_item_aux_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childtask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='childtask',
            name='childtask',
        ),
        migrations.RemoveField(
            model_name='childtask',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ChildTask',
        ),
    ]
